# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AuthResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, message: str=None, token: str=None, token_type: str=None):  # noqa: E501
        """AuthResponse - a model defined in Swagger

        :param message: The message of this AuthResponse.  # noqa: E501
        :type message: str
        :param token: The token of this AuthResponse.  # noqa: E501
        :type token: str
        :param token_type: The token_type of this AuthResponse.  # noqa: E501
        :type token_type: str
        """
        self.swagger_types = {
            'message': str,
            'token': str,
            'token_type': str
        }

        self.attribute_map = {
            'message': 'message',
            'token': 'token',
            'token_type': 'token_type'
        }
        self._message = message
        self._token = token
        self._token_type = token_type

    @classmethod
    def from_dict(cls, dikt) -> 'AuthResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AuthResponse of this AuthResponse.  # noqa: E501
        :rtype: AuthResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this AuthResponse.


        :return: The message of this AuthResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this AuthResponse.


        :param message: The message of this AuthResponse.
        :type message: str
        """

        self._message = message

    @property
    def token(self) -> str:
        """Gets the token of this AuthResponse.


        :return: The token of this AuthResponse.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token: str):
        """Sets the token of this AuthResponse.


        :param token: The token of this AuthResponse.
        :type token: str
        """

        self._token = token

    @property
    def token_type(self) -> str:
        """Gets the token_type of this AuthResponse.


        :return: The token_type of this AuthResponse.
        :rtype: str
        """
        return self._token_type

    @token_type.setter
    def token_type(self, token_type: str):
        """Sets the token_type of this AuthResponse.


        :param token_type: The token_type of this AuthResponse.
        :type token_type: str
        """

        self._token_type = token_type
