# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BookInput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, title: str=None, author: str=None):  # noqa: E501
        """BookInput - a model defined in Swagger

        :param title: The title of this BookInput.  # noqa: E501
        :type title: str
        :param author: The author of this BookInput.  # noqa: E501
        :type author: str
        """
        self.swagger_types = {
            'title': str,
            'author': str
        }

        self.attribute_map = {
            'title': 'title',
            'author': 'author'
        }
        self._title = title
        self._author = author

    @classmethod
    def from_dict(cls, dikt) -> 'BookInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BookInput of this BookInput.  # noqa: E501
        :rtype: BookInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this BookInput.


        :return: The title of this BookInput.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this BookInput.


        :param title: The title of this BookInput.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def author(self) -> str:
        """Gets the author of this BookInput.


        :return: The author of this BookInput.
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author: str):
        """Sets the author of this BookInput.


        :param author: The author of this BookInput.
        :type author: str
        """
        if author is None:
            raise ValueError("Invalid value for `author`, must not be `None`")  # noqa: E501

        self._author = author
