# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.book import Book  # noqa: F401,E501
from swagger_server import util


class BookResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, message: str=None, book_id: int=None, book: Book=None):  # noqa: E501
        """BookResponse - a model defined in Swagger

        :param message: The message of this BookResponse.  # noqa: E501
        :type message: str
        :param book_id: The book_id of this BookResponse.  # noqa: E501
        :type book_id: int
        :param book: The book of this BookResponse.  # noqa: E501
        :type book: Book
        """
        self.swagger_types = {
            'message': str,
            'book_id': int,
            'book': Book
        }

        self.attribute_map = {
            'message': 'message',
            'book_id': 'book_id',
            'book': 'book'
        }
        self._message = message
        self._book_id = book_id
        self._book = book

    @classmethod
    def from_dict(cls, dikt) -> 'BookResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BookResponse of this BookResponse.  # noqa: E501
        :rtype: BookResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this BookResponse.


        :return: The message of this BookResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this BookResponse.


        :param message: The message of this BookResponse.
        :type message: str
        """

        self._message = message

    @property
    def book_id(self) -> int:
        """Gets the book_id of this BookResponse.


        :return: The book_id of this BookResponse.
        :rtype: int
        """
        return self._book_id

    @book_id.setter
    def book_id(self, book_id: int):
        """Sets the book_id of this BookResponse.


        :param book_id: The book_id of this BookResponse.
        :type book_id: int
        """

        self._book_id = book_id

    @property
    def book(self) -> Book:
        """Gets the book of this BookResponse.


        :return: The book of this BookResponse.
        :rtype: Book
        """
        return self._book

    @book.setter
    def book(self, book: Book):
        """Sets the book of this BookResponse.


        :param book: The book of this BookResponse.
        :type book: Book
        """

        self._book = book
