# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.pagination_metadata import PaginationMetadata  # noqa: F401,E501
from swagger_server.models.review import Review  # noqa: F401,E501
from swagger_server import util


class PagedReviewList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: Dict[str, Review]=None, pagination: PaginationMetadata=None):  # noqa: E501
        """PagedReviewList - a model defined in Swagger

        :param data: The data of this PagedReviewList.  # noqa: E501
        :type data: Dict[str, Review]
        :param pagination: The pagination of this PagedReviewList.  # noqa: E501
        :type pagination: PaginationMetadata
        """
        self.swagger_types = {
            'data': Dict[str, Review],
            'pagination': PaginationMetadata
        }

        self.attribute_map = {
            'data': 'data',
            'pagination': 'pagination'
        }
        self._data = data
        self._pagination = pagination

    @classmethod
    def from_dict(cls, dikt) -> 'PagedReviewList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PagedReviewList of this PagedReviewList.  # noqa: E501
        :rtype: PagedReviewList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> Dict[str, Review]:
        """Gets the data of this PagedReviewList.

        Tập hợp các đối tượng nhận xét (key là ID nhận xét).  # noqa: E501

        :return: The data of this PagedReviewList.
        :rtype: Dict[str, Review]
        """
        return self._data

    @data.setter
    def data(self, data: Dict[str, Review]):
        """Sets the data of this PagedReviewList.

        Tập hợp các đối tượng nhận xét (key là ID nhận xét).  # noqa: E501

        :param data: The data of this PagedReviewList.
        :type data: Dict[str, Review]
        """

        self._data = data

    @property
    def pagination(self) -> PaginationMetadata:
        """Gets the pagination of this PagedReviewList.


        :return: The pagination of this PagedReviewList.
        :rtype: PaginationMetadata
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination: PaginationMetadata):
        """Sets the pagination of this PagedReviewList.


        :param pagination: The pagination of this PagedReviewList.
        :type pagination: PaginationMetadata
        """

        self._pagination = pagination
