# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.book import Book  # noqa: F401,E501
from swagger_server.models.pagination_metadata import PaginationMetadata  # noqa: F401,E501
from swagger_server import util


class PagedBookList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: Dict[str, Book]=None, pagination: PaginationMetadata=None):  # noqa: E501
        """PagedBookList - a model defined in Swagger

        :param data: The data of this PagedBookList.  # noqa: E501
        :type data: Dict[str, Book]
        :param pagination: The pagination of this PagedBookList.  # noqa: E501
        :type pagination: PaginationMetadata
        """
        self.swagger_types = {
            'data': Dict[str, Book],
            'pagination': PaginationMetadata
        }

        self.attribute_map = {
            'data': 'data',
            'pagination': 'pagination'
        }
        self._data = data
        self._pagination = pagination

    @classmethod
    def from_dict(cls, dikt) -> 'PagedBookList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PagedBookList of this PagedBookList.  # noqa: E501
        :rtype: PagedBookList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> Dict[str, Book]:
        """Gets the data of this PagedBookList.

        Tập hợp các đối tượng sách (key là ID sách).  # noqa: E501

        :return: The data of this PagedBookList.
        :rtype: Dict[str, Book]
        """
        return self._data

    @data.setter
    def data(self, data: Dict[str, Book]):
        """Sets the data of this PagedBookList.

        Tập hợp các đối tượng sách (key là ID sách).  # noqa: E501

        :param data: The data of this PagedBookList.
        :type data: Dict[str, Book]
        """

        self._data = data

    @property
    def pagination(self) -> PaginationMetadata:
        """Gets the pagination of this PagedBookList.


        :return: The pagination of this PagedBookList.
        :rtype: PaginationMetadata
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination: PaginationMetadata):
        """Sets the pagination of this PagedBookList.


        :param pagination: The pagination of this PagedBookList.
        :type pagination: PaginationMetadata
        """

        self._pagination = pagination
