# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PaginationMetadata(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, total_count: int=None, current_items: int=None, offset: int=None, limit: int=None, next_offset: int=None):  # noqa: E501
        """PaginationMetadata - a model defined in Swagger

        :param total_count: The total_count of this PaginationMetadata.  # noqa: E501
        :type total_count: int
        :param current_items: The current_items of this PaginationMetadata.  # noqa: E501
        :type current_items: int
        :param offset: The offset of this PaginationMetadata.  # noqa: E501
        :type offset: int
        :param limit: The limit of this PaginationMetadata.  # noqa: E501
        :type limit: int
        :param next_offset: The next_offset of this PaginationMetadata.  # noqa: E501
        :type next_offset: int
        """
        self.swagger_types = {
            'total_count': int,
            'current_items': int,
            'offset': int,
            'limit': int,
            'next_offset': int
        }

        self.attribute_map = {
            'total_count': 'total_count',
            'current_items': 'current_items',
            'offset': 'offset',
            'limit': 'limit',
            'next_offset': 'next_offset'
        }
        self._total_count = total_count
        self._current_items = current_items
        self._offset = offset
        self._limit = limit
        self._next_offset = next_offset

    @classmethod
    def from_dict(cls, dikt) -> 'PaginationMetadata':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PaginationMetadata of this PaginationMetadata.  # noqa: E501
        :rtype: PaginationMetadata
        """
        return util.deserialize_model(dikt, cls)

    @property
    def total_count(self) -> int:
        """Gets the total_count of this PaginationMetadata.


        :return: The total_count of this PaginationMetadata.
        :rtype: int
        """
        return self._total_count

    @total_count.setter
    def total_count(self, total_count: int):
        """Sets the total_count of this PaginationMetadata.


        :param total_count: The total_count of this PaginationMetadata.
        :type total_count: int
        """

        self._total_count = total_count

    @property
    def current_items(self) -> int:
        """Gets the current_items of this PaginationMetadata.


        :return: The current_items of this PaginationMetadata.
        :rtype: int
        """
        return self._current_items

    @current_items.setter
    def current_items(self, current_items: int):
        """Sets the current_items of this PaginationMetadata.


        :param current_items: The current_items of this PaginationMetadata.
        :type current_items: int
        """

        self._current_items = current_items

    @property
    def offset(self) -> int:
        """Gets the offset of this PaginationMetadata.


        :return: The offset of this PaginationMetadata.
        :rtype: int
        """
        return self._offset

    @offset.setter
    def offset(self, offset: int):
        """Sets the offset of this PaginationMetadata.


        :param offset: The offset of this PaginationMetadata.
        :type offset: int
        """

        self._offset = offset

    @property
    def limit(self) -> int:
        """Gets the limit of this PaginationMetadata.


        :return: The limit of this PaginationMetadata.
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit: int):
        """Sets the limit of this PaginationMetadata.


        :param limit: The limit of this PaginationMetadata.
        :type limit: int
        """

        self._limit = limit

    @property
    def next_offset(self) -> int:
        """Gets the next_offset of this PaginationMetadata.


        :return: The next_offset of this PaginationMetadata.
        :rtype: int
        """
        return self._next_offset

    @next_offset.setter
    def next_offset(self, next_offset: int):
        """Sets the next_offset of this PaginationMetadata.


        :param next_offset: The next_offset of this PaginationMetadata.
        :type next_offset: int
        """

        self._next_offset = next_offset
