# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ReviewInput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, rating: int=None, comment: str=None):  # noqa: E501
        """ReviewInput - a model defined in Swagger

        :param rating: The rating of this ReviewInput.  # noqa: E501
        :type rating: int
        :param comment: The comment of this ReviewInput.  # noqa: E501
        :type comment: str
        """
        self.swagger_types = {
            'rating': int,
            'comment': str
        }

        self.attribute_map = {
            'rating': 'rating',
            'comment': 'comment'
        }
        self._rating = rating
        self._comment = comment

    @classmethod
    def from_dict(cls, dikt) -> 'ReviewInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ReviewInput of this ReviewInput.  # noqa: E501
        :rtype: ReviewInput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def rating(self) -> int:
        """Gets the rating of this ReviewInput.


        :return: The rating of this ReviewInput.
        :rtype: int
        """
        return self._rating

    @rating.setter
    def rating(self, rating: int):
        """Sets the rating of this ReviewInput.


        :param rating: The rating of this ReviewInput.
        :type rating: int
        """
        if rating is None:
            raise ValueError("Invalid value for `rating`, must not be `None`")  # noqa: E501

        self._rating = rating

    @property
    def comment(self) -> str:
        """Gets the comment of this ReviewInput.


        :return: The comment of this ReviewInput.
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment: str):
        """Sets the comment of this ReviewInput.


        :param comment: The comment of this ReviewInput.
        :type comment: str
        """

        self._comment = comment
