# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.review import Review  # noqa: F401,E501
from swagger_server import util


class ReviewResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, message: str=None, review_id: int=None, review: Review=None):  # noqa: E501
        """ReviewResponse - a model defined in Swagger

        :param message: The message of this ReviewResponse.  # noqa: E501
        :type message: str
        :param review_id: The review_id of this ReviewResponse.  # noqa: E501
        :type review_id: int
        :param review: The review of this ReviewResponse.  # noqa: E501
        :type review: Review
        """
        self.swagger_types = {
            'message': str,
            'review_id': int,
            'review': Review
        }

        self.attribute_map = {
            'message': 'message',
            'review_id': 'review_id',
            'review': 'review'
        }
        self._message = message
        self._review_id = review_id
        self._review = review

    @classmethod
    def from_dict(cls, dikt) -> 'ReviewResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ReviewResponse of this ReviewResponse.  # noqa: E501
        :rtype: ReviewResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this ReviewResponse.


        :return: The message of this ReviewResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this ReviewResponse.


        :param message: The message of this ReviewResponse.
        :type message: str
        """

        self._message = message

    @property
    def review_id(self) -> int:
        """Gets the review_id of this ReviewResponse.


        :return: The review_id of this ReviewResponse.
        :rtype: int
        """
        return self._review_id

    @review_id.setter
    def review_id(self, review_id: int):
        """Sets the review_id of this ReviewResponse.


        :param review_id: The review_id of this ReviewResponse.
        :type review_id: int
        """

        self._review_id = review_id

    @property
    def review(self) -> Review:
        """Gets the review of this ReviewResponse.


        :return: The review of this ReviewResponse.
        :rtype: Review
        """
        return self._review

    @review.setter
    def review(self, review: Review):
        """Sets the review of this ReviewResponse.


        :param review: The review of this ReviewResponse.
        :type review: Review
        """

        self._review = review
