# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Review(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, book_id: int=None, user: str=None, rating: int=None, comment: str=None):  # noqa: E501
        """Review - a model defined in Swagger

        :param book_id: The book_id of this Review.  # noqa: E501
        :type book_id: int
        :param user: The user of this Review.  # noqa: E501
        :type user: str
        :param rating: The rating of this Review.  # noqa: E501
        :type rating: int
        :param comment: The comment of this Review.  # noqa: E501
        :type comment: str
        """
        self.swagger_types = {
            'book_id': int,
            'user': str,
            'rating': int,
            'comment': str
        }

        self.attribute_map = {
            'book_id': 'book_id',
            'user': 'user',
            'rating': 'rating',
            'comment': 'comment'
        }
        self._book_id = book_id
        self._user = user
        self._rating = rating
        self._comment = comment

    @classmethod
    def from_dict(cls, dikt) -> 'Review':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Review of this Review.  # noqa: E501
        :rtype: Review
        """
        return util.deserialize_model(dikt, cls)

    @property
    def book_id(self) -> int:
        """Gets the book_id of this Review.

        ID của sách được đánh giá  # noqa: E501

        :return: The book_id of this Review.
        :rtype: int
        """
        return self._book_id

    @book_id.setter
    def book_id(self, book_id: int):
        """Sets the book_id of this Review.

        ID của sách được đánh giá  # noqa: E501

        :param book_id: The book_id of this Review.
        :type book_id: int
        """

        self._book_id = book_id

    @property
    def user(self) -> str:
        """Gets the user of this Review.

        Vai trò người dùng đã đánh giá  # noqa: E501

        :return: The user of this Review.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user: str):
        """Sets the user of this Review.

        Vai trò người dùng đã đánh giá  # noqa: E501

        :param user: The user of this Review.
        :type user: str
        """

        self._user = user

    @property
    def rating(self) -> int:
        """Gets the rating of this Review.


        :return: The rating of this Review.
        :rtype: int
        """
        return self._rating

    @rating.setter
    def rating(self, rating: int):
        """Sets the rating of this Review.


        :param rating: The rating of this Review.
        :type rating: int
        """

        self._rating = rating

    @property
    def comment(self) -> str:
        """Gets the comment of this Review.


        :return: The comment of this Review.
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment: str):
        """Sets the comment of this Review.


        :param comment: The comment of this Review.
        :type comment: str
        """

        self._comment = comment
